In [1]:
import numpy as np

## Matrices and Vectors
**Matrix**

In [7]:
matrix = np.array([[1 ,2 ,3],
                   [4 ,5 ,6],
                   [7 ,8 ,9],
                   [10 ,11 ,12]])

In [9]:
vector = np.array([[1],
                  [2],
                  [3]])

In [33]:
matrix[1,2]

6

In [13]:
matrix.size

12

In [15]:
matrix.view()

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
matrix.argmax()

11

In [21]:
matrix.argmin()

0

In [23]:
matrix.max()

12

In [24]:
matrix.min()

1

In [25]:
matrix.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

**Vector**

In [34]:
vector[1,0]

2

In [26]:
vector.size

3

In [27]:
vector.view()

array([[1],
       [2],
       [3]])

In [28]:
vector.argmax()

2

In [29]:
vector.argmin()

0

In [30]:
vector.max()

3

In [31]:
vector.min()

1

In [32]:
vector.T

array([[1, 2, 3]])

## Addition and Scalar Multiplication
**Matrix**

In [35]:
matrix_1 = np.array([[1 ,2 ,3],
                   [4 ,5 ,6],
                   [7 ,8 ,9],
                   [10 ,11 ,12]])

In [36]:
matrix_2 = np.array([[1 ,2 ,3],
                   [4 ,5 ,6],
                   [7 ,8 ,9],
                   [10 ,11 ,12]])

In [52]:
matrix_3 = np.array([[11 ,2 ,3],
                   [4 ,33 ,6],
                   [7 ,66 ,9],
                   [10 ,22 ,12]])

In [37]:
matrix_1 + matrix_2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [38]:
matrix_1 - matrix_2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [39]:
matrix_1 * matrix_2

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [40]:
matrix_1 / matrix_2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [53]:
matrix_1 * 3 + matrix_2 / 4 - matrix_3

array([[ -8,   4,   6],
       [  9, -17,  13],
       [ 15, -40,  20],
       [ 22,  13,  27]])

**Vector**

In [41]:
vector_1 = np.array([[1],
                  [2],
                  [3]])

In [42]:
vector_2 = np.array([[1],
                  [2],
                  [3]])

In [50]:
vector_3 = np.array([[2],
                  [4],
                  [6]])

In [43]:
vector_1 + vector_2

array([[2],
       [4],
       [6]])

In [44]:
vector_1 - vector_2

array([[0],
       [0],
       [0]])

In [45]:
vector_1 * vector_2

array([[1],
       [4],
       [9]])

In [46]:
vector_1 / vector_2

array([[1],
       [1],
       [1]])

In [51]:
vector_1 * 3 + vector_2 / 4 - vector_3

array([[1],
       [2],
       [3]])

## Matrix-Vector Multiplication

In [59]:
matrix.dot(vector)

array([[14],
       [32],
       [50],
       [68]])

## Matrix-Matrix Multiplication

In [65]:
matrix_1 = np.array([[1 ,2] , [3 ,4] , [5 ,6]])

In [66]:
matrix_2 = np.array([[1] , [2]])

In [68]:
matrix_1.dot(matrix_2) 

array([[ 5],
       [11],
       [17]])

## Matrix Multiplication Properties

In [82]:
matrix_1 = np.array([[2 ,4 , 6] , [8 ,10 ,12] , [14 ,16 , 18]])

In [83]:
matrix_2 = np.array([[1 ,3 , 5] , [7 ,9 , 11] , [13 ,15 , 17]])

In [109]:
matrix_3 = np.array([[1 ,3 , 3] , [1 ,4 ,3] , [1 ,3 , 4]])

In [87]:
matrix_1.dot(matrix_2)

array([[108, 132, 156],
       [234, 294, 354],
       [360, 456, 552]])

In [86]:
matrix_2.dot(matrix_1)

array([[ 96, 114, 132],
       [240, 294, 348],
       [384, 474, 564]])

In [89]:
a = matrix_1.dot(matrix_2)
a.dot(matrix_3)

array([[1728, 2124, 2520],
       [3888, 4770, 5652],
       [6048, 7416, 8784]])

In [90]:
a = matrix_3.dot(matrix_2)
a.dot(matrix_1)

array([[1728, 2124, 2520],
       [3888, 4770, 5652],
       [6048, 7416, 8784]])

In [95]:
np.identity(1)

array([[1.]])

In [96]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [100]:
i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [102]:
matrix_1.dot(i) == matrix_1 

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [103]:
matrix_1i.dot(matrix_1) == matrix_1 

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Inverse and Transpose

In [112]:
mat3_invers = np.linalg.inv(matrix_3)

In [113]:
mat3_invers

array([[ 7., -3., -3.],
       [-1.,  1.,  0.],
       [-1.,  0.,  1.]])

In [114]:
mat3_invers.dot(matrix_3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [115]:
matrix_4 = np.array([[3 ,4 ], [2 , 16]])

In [116]:
mat4_invers = np.linalg.inv(matrix_4)

In [117]:
mat4_invers

array([[ 0.4  , -0.1  ],
       [-0.05 ,  0.075]])

In [118]:
mat4_invers.dot(matrix_4)

array([[1., 0.],
       [0., 1.]])

In [119]:
matrix_5 = np.array([[1 , 2 , 0] , [3  , 5 , 9]])

In [120]:
matrix_5

array([[1, 2, 0],
       [3, 5, 9]])

In [121]:
matrix_5.T

array([[1, 3],
       [2, 5],
       [0, 9]])