In [1]:
import numpy as np

## Number 1

In [2]:
A = np.array([[4 , 3],[6 , 9]])
B = np.array([[-2 ,9],[-5 , 2]])

In [3]:
A - B

array([[ 6, -6],
       [11,  7]])

## Number 2

In [4]:
x = np.array([[5], [5] , [2] , [7]])

In [5]:
x

array([[5],
       [5],
       [2],
       [7]])

In [6]:
2 * x

array([[10],
       [10],
       [ 4],
       [14]])

## Number 3

In [7]:
u = np.array([[3], [5] , [1]])

In [9]:
u

array([[3],
       [5],
       [1]])

In [8]:
u.T

array([[3, 5, 1]])

## Number 4

In [16]:
u = np.array([[4], [-4] , [-3]])
v = np.array([[4], [2] , [4]])

In [17]:
u

array([[ 4],
       [-4],
       [-3]])

In [18]:
v

array([[4],
       [2],
       [4]])

In [19]:
u_transpose = u.T

In [20]:
u_transpose

array([[ 4, -4, -3]])

In [21]:
u_transpose.dot(v)

array([[-4]])

## Number 5

In [23]:
A = np.identity(3)
B = np.identity(3)

In [24]:
A.dot(B)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
B.dot(A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])